### ISSUE TITLE
fix feedstock meta.yaml and setup.py

### ISSUE THREAD

**Issue by Sparks29032** [regro/regolith#1053]
- [ ] Remove scopatz in links (replace with regro)
- [ ] Put license in spx format
- [ ] Update python versions >=3.7 to >=3.10
