### ISSUE TITLE
updates to todo lister and updater

### ISSUE THREAD

**Issue by sbillinge** [regro/regolith#572]
- [ ] First gripe - I think it would be helpful if hte l_todo and the u_todo (and the f_todo) return the same list or it is very confusing....I see something I want to finish/update in my l_todo list, so I run ``f_todo`` or ``u_todo`` and then I can't find it in that list to get the index.   I realize that this is tricky because of the presence of milestones in here.  but I am just pointing out actual/desired behavior. 

- [ ] please remove ``begin-date`` (who cares) and ``end-date`` (we are now only returning open items so they all have ``None`` here) from what is reported in the ``u_todo`` list.  Not sure what the f_todo list looks like, but it should have the same desired behavior.  Ideally, all three programs call the same function to generate the list?  

- [ ] Actually, since we want the lists generated in these different ways to be as consistent as possible, can you make what is returned in the parens to be the 

- [ ] Possible bug...I ran the finisher and it showed me a list.  #14 said ``test``.  to test the finisher I then typed ``rh f_todo -i 14``.   the finisher ran but it said ``The task "new coeditor tasks for Nicola" for sbillinge has been marked as finished in people collection.``, which is different from ``test``.  Checking the people db the finisher had actually behaved correctly, as ``test`` entry in todos was set to finished, and the new tasks for Nicola entry was still status ``started``, but the print message does need to be fixed.

- [ ] ple

**Comment by jiaweizang** [comment]
@sbillinge For the first problem, there may be 2 ways to fix, one is to print milestones and todo tasks separately, so the index of todo tasks are the same as f_todo and u_todo. Another way is to keep mixing them, and change f_todo and u_todo. For example, if we enter the index of a milestone, the helper will update milestones in projecta collection. To realize this function, I'm not sure if we should copy codes from u_milestones to u_todo, or just send it to u_milestones through some ways.

**Comment by sbillinge** [comment]
> 
> 
> @sbillinge For the first problem, there may be 2 ways to fix, one is to print milestones and todo tasks separately, so the index of todo tasks are the same as f_todo and u_todo. Another way is to keep mixing them, and change f_todo and u_todo. For example, if we enter the index of a milestone, the helper will update milestones in projecta collection. To realize this function, I'm not sure if we should copy codes from u_milestones to u_todo, or just send it to u_milestones through some ways.

I am not sure what is best tbh. Maybe just separate todos from milestones etc.  Maybe you can put all the "other" types of things together though.  rn it is just milestones, but soon it will also be proprevs and manurevs, and later even recletts and possibly other things.  If they are all in a properly ranked list I think it is ok to have two lists for now.
