### ISSUE TITLE
milestone updater uses uuid to select which milestone to update

### ISSUE THREAD

**Issue by sbillinge** [regro/regolith#987]
nothing else changes as to how it updates.  In each case, write tests first and get the reviewed, then write code.

- [ ] make uuid fragment an optional cl arg
- [ ] make prum _id an optional requirement (change from currently it being required)
- [ ] if no uuid, assume it wants to add a milestone and look for the prum_id
- [ ] if no prum_id assume it will update an existing milestone and follow that flow
- [ ] if both exit gracefully (with info to user about what went wrong and what they should do to put it right)
- [ ] if neither exit gracefully
- [ ] update the updating logic so the tests pass.  It will mostly be messing with existing flow logic (iterating over prums and things).  We are not yet working on making the actual updating logic easier to use.  That comes later.
- [ ] add rever news
- [ ] remove the listing capability (we will list using milestone lister now)
- [ ] make sure all tests pass

**Comment by dpeters001** [comment]
Dom will take this.
