### ISSUE TITLE
new milestones tasks logic in a_todos

### ISSUE THREAD

**Issue by sbillinge** [regro/regolith#988]
modify a_todos so a todo item can be assigned to a milestone as an option (by giving a milestone uuid fragment).  Write tests for everything first, get them reviewed then write the code

- [x] add milestone uuid to cli parser
- [x] write a function in regolith tools module that does the adding (this will be reused in other places)
- [x] if rc.milestone_uuid then trigger logic that adds the uuid of this task to the task list of the given milestone and updates that prum (get that logic from u_milestones...`rc.client.update_one()`)
- [x] news

**Comment by dpeters001** [comment]
Dom will take this.
